[#ftl]
[@b.head/]
[@b.toolbar title="修改课程分组"]bar.addBack();[/@]
[@b.tabs]
  [#assign sa][#if courseGroup.persisted]!update?id=${courseGroup.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.textfield name="courseGroup.code" label="代码" value="${courseGroup.code!}" required="true" maxlength="20"/]
    [@b.textfield name="courseGroup.name" label="名称" value="${courseGroup.name!}" required="true" maxlength="20"/]
    [@b.select label="上级课程组" name="parent.id" value=(courseGroup.parent)! style="width:200px;"  items=parents option="id,name" empty="..."/]
    [@b.number label="同级顺序号" name="indexno" value="${courseGroup.lastindex!}" required="true" maxlength="2" min="1" max="100" /]
    [@b.startend label="有效期限"
      name="courseGroup.beginOn,courseGroup.endOn" required="true,false"
      start=courseGroup.beginOn end=courseGroup.endOn format="date"/]
    [@b.textfield name="courseGroup.remark" label="备注" value="${courseGroup.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
