[#ftl]
[@b.head/]
[@b.toolbar title="维护课程分组"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action="!saveGroup" theme="list"]
		<input type="hidden" name="metaIds" value="${metaIds}"/>
    [@b.select name="courseGroup.id" label="课程分组" items=courseGroups?sort_by("code")  option="id,name" empty="..."/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
