[#ftl]
[@b.head/]
[@b.grid  items=courseBlogMetas var="courseBlogMeta"]
  [@b.gridbar]
    bar.addItem("批量编辑课程分组",action.multi('editGroup'));
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="15%" property="course.code" title="课程代码"/]
    [@b.col width="20%" property="course.name" title="课程名称"/]
    [@b.col width="15%" property="course.credits" title="学分"/]
    [@b.col width="15%" property="course.courseType.name" title="课程类别"/]
    [@b.col width="15%" property="courseGroup.name" title="课程分组"/]
    [@b.col width="15%" property="author.name" title="最近更新作者"/]
  [/@]
[/@]
[@b.foot/]