[#ftl]
[@b.head/]
[@b.toolbar title="修改获奖课程明细"]bar.addBack();[/@]
[@b.tabs]
  [#assign sa][#if awardLabel.persisted]!update?id=${awardLabel.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [@b.textfield name="awardLabel.code" label="代码" value="${awardLabel.code!}" required="true" maxlength="20"/]
    [@b.textfield name="awardLabel.name" label="名称" value="${awardLabel.name!}" required="true" maxlength="20"/]
    [@b.select label="获奖课程类别" name="awardLabel.labelType.id" value=(awardLabel.labelType)! style="width:200px;"  items=labelTypes option="id,name" empty="..."/]
    [@b.startend label="有效期限"
      name="awardLabel.beginOn,awardLabel.endOn" required="true,false"
      start=awardLabel.beginOn end=awardLabel.endOn format="date"/]
    [@b.textfield name="awardLabel.remark" label="备注" value="${awardLabel.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
