[#ftl]
[@b.head/]
[@b.toolbar]bar.addBack();[/@]
[@b.tabs]
  [#assign sa][#if reviseSetting.persisted]!update?id=${reviseSetting.id!}[#else]!save[/#if][/#assign]
  [@b.form action=sa theme="list"]
    [#if reviseSetting.persisted]
      [@b.field label="学年学期"]${reviseSetting.semester.schoolYear}学年${reviseSetting.semester.name}学期[/@]
    [#else]
      [@urp_base.semester name="reviseSetting.semester.id" label="学年学期"  value=currentSemester required="true"/]
    [/#if]
    [@b.startend label="有效期限"
      name="reviseSetting.beginAt,reviseSetting.endAt" required="true,false"
      start=reviseSetting.beginAt end=reviseSetting.endAt format="yyyy-MM-dd HH:mm"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
