[#ftl]
[@b.head/]
[@b.grid  items=reviseTasks var="reviseTask"]
  [@b.row]
    [@b.col width="20%" property="course.code" title="课程代码"/]
    [@b.col width="20%" property="course.name" title="课程名称"/]
    [@b.col width="20%" property="course.department.name" title="开课院系"/]
    [@b.col width="25%"  title="课程资料"]
      [#if courseBlogMap.get(reviseTask)??]
        [#if reviseSetting?? && (courseBlogMap.get(reviseTask).status = BlogStatus.Draft || courseBlogMap.get(reviseTask).status = BlogStatus.Unpassed)]
          [@b.a href="!edit?id=${reviseTask.id!}"]修改[/@]
          [@b.a href="!remove?id=${reviseTask.id!}"]删除[/@]
          [@b.a href="!submit?id=${reviseTask.id!}"]提交审核[/@]
        [/#if]
        [@b.a href="course-blog!info?id=${courseBlogMap.get(reviseTask).id!}" target="_blank"]查看[/@]
      [#elseif reviseSetting??]
        [@b.a href="!edit?id=${reviseTask.id!}"]新增[/@]
      [#else ]不在可编辑课程资料时间范围内
      [/#if]
    [/@]
    [@b.col width="15%" title="状态"]
      [#if courseBlogMap.get(reviseTask)??]
        ${(courseBlogMap.get(reviseTask).status.name)!}
      [/#if]
    [/@]
  [/@]
[/@]
<br><br><br><br>
[#include "courseBlogList.ftl" /]
[@b.foot/]